// Action Types
export default {
  // Loader
  START_LOADER: '@loader/START_LOADER',
  STOP_LOADER: '@loader/STOP_LOADER',

  // Login
  POST_LOGIN_ACTION: '@login/POST_LOGIN_ACTION',
  POST_LOGIN_REQUEST: '@login/POST_LOGIN_REQUEST',
  POST_LOGIN_SUCCESS: '@login/POST_LOGIN_SUCCESS',
  POST_LOGIN_FAILURE: '@login/POST_LOGIN_FAILURE',
  POST_LOGIN_CLEAR: '@login/POST_LOGIN_CLEAR',
  SET_MERCHANT_INFO: '@admin/SET_MERCHANT_INFO',
  CLEAR_MERCHANT_INFO: '@admin/CLEAR_MERCHANT_INFO',
  SET_EXPIRY_TOKEN_NOTIFICATION: '@login/SET_EXPIRY_TOKEN_NOTIFICATION',
  SET_USER_DATA: 'SET_USER_DATA',

  // Login otp
  GET_LOGIN_OTP: '@login/GET_LOGIN_OTP',
  GET_LOGIN_OTP_REQUEST: '@login/GET_LOGIN_OTP_REQUEST',
  GET_LOGIN_OTP_SUCCESS: '@login/GET_LOGIN_OTP_SUCCESS',
  GET_LOGIN_OTP_FAILURE: '@login/GET_LOGIN_OTP_FAILURE',
  GET_LOGIN_OTP_CLEAR: '@login/GET_LOGIN_OTP_CLEAR',
  RESEND_LOGIN_OTP: '@login/RESEND_LOGIN_OTP',
  RESEND_LOGIN_OTP_REQUEST: '@login/RESEND_LOGIN_OTP_REQUEST',
  RESEND_LOGIN_OTP_SUCCESS: '@login/RESEND_LOGIN_OTP_SUCCESS',
  RESEND_LOGIN_OTP_FAILURE: '@login/RESEND_LOGIN_OTP_FAILURE',
  RESEND_LOGIN_OTP_CLEAR: '@login/RESEND_LOGIN_OTP_CLEAR',
  VALIDATE_LOGIN_OTP: '@login/VALIDATE_LOGIN_OTP',
  VALIDATE_LOGIN_OTP_REQUEST: '@login/VALIDATE_LOGIN_OTP_REQUEST',
  VALIDATE_LOGIN_OTP_SUCCESS: '@login/VALIDATE_LOGIN_OTP_SUCCESS',
  VALIDATE_LOGIN_OTP_FAILURE: '@login/VALIDATE_LOGIN_OTP_FAILURE',
  VALIDATE_LOGIN_OTP_CLEAR: '@login/VALIDATE_LOGIN_OTP_CLEAR',

  // New SignUp
  POST_NEW_SIGN_UP_ACTION: '@newSignUp/POST_NEW_SIGN_UP_ACTION',
  POST_NEW_SIGN_UP_REQUEST: '@newSignUp/POST_NEW_SIGN_UP_REQUEST',
  POST_NEW_SIGN_UP_SUCCESS: '@newSignUp/POST_NEW_SIGN_UP_SUCCESS',
  POST_NEW_SIGN_UP_FAILURE: '@newSignUp/POST_NEW_SIGN_UP_FAILURE',
  POST_NEW_SIGN_UP_CLEAR: '@newSignUp/POST_NEW_SIGN_UP_CLEAR',

  // Logout
  POST_LOGOUT_ACTION: '@logout/POST_LOGOUT_ACTION',
  POST_LOGOUT_REQUEST: '@logout/POST_LOGOUT_REQUEST',
  POST_LOGOUT_SUCCESS: '@logout/POST_LOGOUT_SUCCESS',
  POST_LOGOUT_FAILURE: '@logout/POST_LOGOUT_FAILURE',
  POST_LOGOUT_CLEAR: '@logout/POST_LOGOUT_CLEAR',

  // Refresh TOken
  POST_REFRESH_TOKEN_ACTION: '@refresh-token/POST_REFRESH_TOKEN_ACTION',
  POST_REFRESH_TOKEN_REQUEST: '@refresh-token/POST_REFRESH_TOKEN_REQUEST',
  POST_REFRESH_TOKEN_SUCCESS: '@refresh-token/POST_REFRESH_TOKEN_SUCCESS',
  POST_REFRESH_TOKEN_FAILURE: '@refresh-token/POST_REFRESH_TOKEN_FAILURE',
  POST_REFRESH_TOKEN_CLEAR: '@refresh-token/POST_REFRESH_TOKEN_CLEAR',

  // Forgot password
  POST_FORGET_PASSWORD_ACTION: '@forget-password/POST_FORGET_PASSWORD_ACTION',
  POST_FORGET_PASSWORD_REQUEST: '@forget-password/POST_FORGET_PASSWORD_REQUEST',
  POST_FORGET_PASSWORD_SUCCESS: '@forget-password/POST_FORGET_PASSWORD_SUCCESS',
  POST_FORGET_PASSWORD_FAILURE: '@forget-password/POST_FORGET_PASSWORD_FAILURE',
  POST_FORGET_PASSWORD_CLEAR: '@forget-password/POST_FORGET_PASSWORD_CLEAR',

  // Fetch OTP
  POST_FETCH_OTP_ACTION: '@fetch-otp/POST_FETCH_OTP_ACTION',
  POST_FETCH_OTP_REQUEST: '@fetch-otp/POST_FETCH_OTP_REQUEST',
  POST_FETCH_OTP_SUCCESS: '@fetch-otp/POST_FETCH_OTP_SUCCESS',
  POST_FETCH_OTP_FAILURE: '@fetch-otp/POST_FETCH_OTP_FAILURE',
  POST_FETCH_OTP_CLEAR: '@fetch-otp/POST_FETCH_OTP_CLEAR',

  // Validate OTP
  POST_VALIDATE_OTP_ACTION: '@validate-otp/POST_VALIDATE_OTP_ACTION',
  POST_VALIDATE_OTP_REQUEST: '@validate-otp/POST_VALIDATE_OTP_REQUEST',
  POST_VALIDATE_OTP_SUCCESS: '@validate-otp/POST_VALIDATE_OTP_SUCCESS',
  POST_VALIDATE_OTP_FAILURE: '@validate-otp/POST_VALIDATE_OTP_FAILURE',
  POST_VALIDATE_OTP_CLEAR: '@validate-otp/POST_VALIDATE_OTP_CLEAR',

  // Save new password
  POST_SAVE_NEW_PASSWORD_ACTION:
    '@save-new-password/POST_SAVE_NEW_PASSWORD_ACTION',
  POST_SAVE_NEW_PASSWORD_REQUEST:
    '@save-new-password/POST_SAVE_NEW_PASSWORD_REQUEST',
  POST_SAVE_NEW_PASSWORD_SUCCESS:
    '@save-new-password/POST_SAVE_NEW_PASSWORD_SUCCESS',
  POST_SAVE_NEW_PASSWORD_FAILURE:
    '@save-new-password/POST_SAVE_NEW_PASSWORD_FAILURE',
  POST_SAVE_NEW_PASSWORD_CLEAR:
    '@save-new-password/POST_SAVE_NEW_PASSWORD_CLEAR',

  // Sign Up
  POST_SIGN_UP_ACTION: '@signup/POST_SIGN_UP_ACTION',
  POST_SIGN_UP_REQUEST: '@signup/POST_SIGN_UP_REQUEST',
  POST_SIGN_UP_SUCCESS: '@signup/POST_SIGN_UP_SUCCESS',
  POST_SIGN_UP_FAILURE: '@signup/POST_SIGN_UP_FAILURE',
  POST_SIGN_UP_CLEAR: '@signup/POST_SIGN_UP_CLEAR',

  // Change password
  POST_CHANGE_PASSWORD_ACTION: '@signup/POST_CHANGE_PASSWORD_ACTION',
  POST_CHANGE_PASSWORD_REQUEST: '@signup/POST_CHANGE_PASSWORD_RCHANGE_PASSWORD',
  POST_CHANGE_PASSWORD_SUCCESS: '@signup/POST_CHANGE_PASSWORD_SUCCESS',
  POST_CHANGE_PASSWORD_FAILURE: '@signup/POST_CHANGE_PASSWORD_FAILURE',
  POST_CHANGE_PASSWORD_CLEAR: '@signup/POST_CHANGE_PASSWORD_CLEAR',

  // Analytics
  POST_ANALYTICS_ACTION: '@analytics/POST_ANALYTICS_ACTION',
  POST_ANALYTICS_REQUEST: '@analytics/POST_ANALYTICS_REQUEST',
  POST_ANALYTICS_SUCCESS: '@analytics/POST_ANALYTICS_SUCCESS',
  POST_ANALYTICS_FAILURE: '@analytics/POST_ANALYTICS_FAILURE',
  POST_ANALYTICS_CLEAR: '@analytics/POST_ANALYTICS_CLEAR',

  // Validation
  POST_VALIDATION_ERRORS_ACTION: '@validation/POST_VALIDATION_ERRORS_ACTION',
  POST_VALIDATION_ERRORS_REQUEST: '@validation/POST_VALIDATION_ERRORS_REQUEST',
  POST_VALIDATION_ERRORS_SUCCESS: '@validation/POST_VALIDATION_ERRORS_SUCCESS',
  POST_VALIDATION_ERRORS_FAILURE: '@validation/POST_VALIDATION_ERRORS_FAILURE',
  POST_VALIDATION_ERRORS_CLEAR: '@validation/POST_VALIDATION_ERRORS_CLEAR',

  // Smart Routing / Get Gateway List
  GET_GATEWAY_LIST_ACTION: '@smart-routing/GET_GATEWAY_LIST_ACTION',
  GET_GATEWAY_LIST_REQUEST: '@smart-routing/GET_GATEWAY_LIST_REQUEST',
  GET_GATEWAY_LIST_SUCCESS: '@smart-routing/GET_GATEWAY_LIST_SUCCESS',
  GET_GATEWAY_LIST_FAILURE: '@smart-routing/GET_GATEWAY_LIST_FAILURE',
  GET_GATEWAY_LIST_CLEAR: '@smart-routing/GET_GATEWAY_LIST_CLEAR',

  // Smart Routing / Get Unmapped Gateway List
  GET_UNMAPPED_GATEWAY_LIST_ACTION:
    '@smart-routing/GET_UNMAPPED_GATEWAY_LIST_ACTION',
  GET_UNMAPPED_GATEWAY_LIST_REQUEST:
    '@smart-routing/GET_UNMAPPED_GATEWAY_LIST_REQUEST',
  GET_UNMAPPED_GATEWAY_LIST_SUCCESS:
    '@smart-routing/GET_UNMAPPED_GATEWAY_LIST_SUCCESS',
  GET_UNMAPPED_GATEWAY_LIST_FAILURE:
    '@smart-routing/GET_UNMAPPED_GATEWAY_LIST_FAILURE',
  GET_UNMAPPED_GATEWAY_LIST_CLEAR:
    '@smart-routing/GET_UNMAPPED_GATEWAY_LIST_CLEAR',

  // Smart Routing / Get Gateway Configurations
  GET_GATEWAY_CONFIGURATIONS_ACTION:
    '@smart-routing/GET_GATEWAY_CONFIGURATIONS_ACTION',
  GET_GATEWAY_CONFIGURATIONS_REQUEST:
    '@smart-routing/GET_GATEWAY_CONFIGURATIONS_REQUEST',
  GET_GATEWAY_CONFIGURATIONS_SUCCESS:
    '@smart-routing/GET_GATEWAY_CONFIGURATIONS_SUCCESS',
  GET_GATEWAY_CONFIGURATIONS_FAILURE:
    '@smart-routing/GET_GATEWAY_CONFIGURATIONS_FAILURE',
  GET_GATEWAY_CONFIGURATIONS_CLEAR:
    '@smart-routing/GET_GATEWAY_CONFIGURATIONS_CLEAR',

  SET_GATEWAY_CONFIGURATIONS_PARAMS:
    '@smart-routing/SET_GATEWAY_CONFIGURATIONS_PARAMS',

  // Save Gateway
  POST_SAVE_GATEWAY_ACTION: '@smart-routing/POST_SAVE_GATEWAY_ACTION',
  POST_SAVE_GATEWAY_REQUEST: '@smart-routing/POST_SAVE_GATEWAY_REQUEST',
  POST_SAVE_GATEWAY_SUCCESS: '@smart-routing/POST_SAVE_GATEWAY_SUCCESS',
  POST_SAVE_GATEWAY_FAILURE: '@smart-routing/POST_SAVE_GATEWAY_FAILURE',
  POST_SAVE_GATEWAY_CLEAR: '@smart-routing/POST_SAVE_GATEWAY_CLEAR',

  // Smart Routing / Get Preference Gateway
  GET_PREFERENCE_GATEWAY_ACTION: '@smart-routing/GET_PREFERENCE_GATEWAY_ACTION',
  GET_PREFERENCE_GATEWAY_REQUEST:
    '@smart-routing/GET_PREFERENCE_GATEWAY_REQUEST',
  GET_PREFERENCE_GATEWAY_SUCCESS:
    '@smart-routing/GET_PREFERENCE_GATEWAY_SUCCESS',
  GET_PREFERENCE_GATEWAY_FAILURE:
    '@smart-routing/GET_PREFERENCE_GATEWAY_FAILURE',
  GET_PREFERENCE_GATEWAY_CLEAR: '@smart-routing/GET_PREFERENCE_GATEWAY_CLEAR',

  // Save Custom Routing Logic
  POST_SAVE_CUSTOM_LOGIC_ACTION: '@smart-routing/POST_SAVE_CUSTOM_LOGIC_ACTION',
  POST_SAVE_CUSTOM_LOGIC_REQUEST:
    '@smart-routing/POST_SAVE_CUSTOM_LOGIC_REQUEST',
  POST_SAVE_CUSTOM_LOGIC_SUCCESS:
    '@smart-routing/POST_SAVE_CUSTOM_LOGIC_SUCCESS',
  POST_SAVE_CUSTOM_LOGIC_FAILURE:
    '@smart-routing/POST_SAVE_CUSTOM_LOGIC_FAILURE',
  POST_SAVE_CUSTOM_LOGIC_CLEAR: '@smart-routing/POST_SAVE_CUSTOM_LOGIC_CLEAR',

  // Smart Routing / Get Active Priority Logic
  GET_ACTIVE_PRIORITY_LOGIC_ACTION:
    '@smart-routing/GET_ACTIVE_PRIORITY_LOGIC_ACTION',
  GET_ACTIVE_PRIORITY_LOGIC_REQUEST:
    '@smart-routing/GET_ACTIVE_PRIORITY_LOGIC_REQUEST',
  GET_ACTIVE_PRIORITY_LOGIC_SUCCESS:
    '@smart-routing/GET_ACTIVE_PRIORITY_LOGIC_SUCCESS',
  GET_ACTIVE_PRIORITY_LOGIC_FAILURE:
    '@smart-routing/GET_ACTIVE_PRIORITY_LOGIC_FAILURE',
  GET_ACTIVE_PRIORITY_LOGIC_CLEAR:
    '@smart-routing/GET_ACTIVE_PRIORITY_LOGIC_CLEAR',

  // Smart Routing / Update Preference Score
  UPDATE_PREFERENCE_SCORE_ACTION:
    '@smart-routing/UPDATE_PREFERENCE_SCORE_ACTION',
  UPDATE_PREFERENCE_SCORE_REQUEST:
    '@smart-routing/UPDATE_PREFERENCE_SCORE_REQUEST',
  UPDATE_PREFERENCE_SCORE_SUCCESS:
    '@smart-routing/UPDATE_PREFERENCE_SCORE_SUCCESS',
  UPDATE_PREFERENCE_SCORE_FAILURE:
    '@smart-routing/UPDATE_PREFERENCE_SCORE_FAILURE',
  UPDATE_PREFERENCE_SCORE_CLEAR: '@smart-routing/UPDATE_PREFERENCE_SCORE_CLEAR',

  // Smart Routing / Get Priority Logics List
  GET_PRIORITY_LOGIC_LIST_ACTION:
    '@smart-routing/GET_PRIORITY_LOGIC_LIST_ACTION',
  GET_PRIORITY_LOGIC_LIST_REQUEST:
    '@smart-routing/GET_PRIORITY_LOGIC_LIST_REQUEST',
  GET_PRIORITY_LOGIC_LIST_SUCCESS:
    '@smart-routing/GET_PRIORITY_LOGIC_LIST_SUCCESS',
  GET_PRIORITY_LOGIC_LIST_FAILURE:
    '@smart-routing/GET_PRIORITY_LOGIC_LIST_FAILURE',
  GET_PRIORITY_LOGIC_LIST_CLEAR: '@smart-routing/GET_PRIORITY_LOGIC_LIST_CLEAR',

  // Smart Routing / Get Preference Score BIN List
  GET_PREFERENCE_SCORE_BIN_LIST_ACTION:
    '@smart-routing/GET_PREFERENCE_SCORE_BIN_LIST_ACTION',
  GET_PREFERENCE_SCORE_BIN_LIST_REQUEST:
    '@smart-routing/GET_PREFERENCE_SCORE_BIN_LIST_REQUEST',
  GET_PREFERENCE_SCORE_BIN_LIST_SUCCESS:
    '@smart-routing/GET_PREFERENCE_SCORE_BIN_LIST_SUCCESS',
  GET_PREFERENCE_SCORE_BIN_LIST_FAILURE:
    '@smart-routing/GET_PREFERENCE_SCORE_BIN_LIST_FAILURE',
  GET_PREFERENCE_SCORE_BIN_LIST_CLEAR:
    '@smart-routing/GET_PREFERENCE_SCORE_BIN_LIST_CLEAR',

  // Smart Routing / Get Preference Score Issuer List
  GET_PREFERENCE_SCORE_ISSUER_LIST_ACTION:
    '@smart-routing/GET_PREFERENCE_SCORE_ISSUER_LIST_ACTION',
  GET_PREFERENCE_SCORE_ISSUER_LIST_REQUEST:
    '@smart-routing/GET_PREFERENCE_SCORE_ISSUER_LIST_REQUEST',
  GET_PREFERENCE_SCORE_ISSUER_LIST_SUCCESS:
    '@smart-routing/GET_PREFERENCE_SCORE_ISSUER_LIST_SUCCESS',
  GET_PREFERENCE_SCORE_ISSUER_LIST_FAILURE:
    '@smart-routing/GET_PREFERENCE_SCORE_ISSUER_LIST_FAILURE',
  GET_PREFERENCE_SCORE_ISSUER_LIST_CLEAR:
    '@smart-routing/GET_PREFERENCE_SCORE_ISSUER_LIST_CLEAR',

  // Smart Routing / Get Preference Score Card Brand List
  GET_PREFERENCE_SCORE_CARD_BRAND_LIST_ACTION:
    '@smart-routing/GET_PREFERENCE_SCORE_CARD_BRAND_LIST_ACTION',
  GET_PREFERENCE_SCORE_CARD_BRAND_LIST_REQUEST:
    '@smart-routing/GET_PREFERENCE_SCORE_CARD_BRAND_LIST_REQUEST',
  GET_PREFERENCE_SCORE_CARD_BRAND_LIST_SUCCESS:
    '@smart-routing/GET_PREFERENCE_SCORE_CARD_BRAND_LIST_SUCCESS',
  GET_PREFERENCE_SCORE_CARD_BRAND_LIST_FAILURE:
    '@smart-routing/GET_PREFERENCE_SCORE_CARD_BRAND_LIST_FAILURE',
  GET_PREFERENCE_SCORE_CARD_BRAND_LIST_CLEAR:
    '@smart-routing/GET_PREFERENCE_SCORE_CARD_BRAND_LIST_CLEAR',

  // Smart Routing / Get All Card Brand Names List
  GET_ALL_CARD_BRAND_NAMES_ACTION:
    '@smart-routing/GET_ALL_CARD_BRAND_NAMES_ACTION',
  GET_ALL_CARD_BRAND_NAMES_REQUEST:
    '@smart-routing/GET_ALL_CARD_BRAND_NAMES_REQUEST',
  GET_ALL_CARD_BRAND_NAMES_SUCCESS:
    '@smart-routing/GET_ALL_CARD_BRAND_NAMES_SUCCESS',
  GET_ALL_CARD_BRAND_NAMES_FAILURE:
    '@smart-routing/GET_ALL_CARD_BRAND_NAMES_FAILURE',
  GET_ALL_CARD_BRAND_NAMES_CLEAR:
    '@smart-routing/GET_ALL_CARD_BRAND_NAMES_CLEAR',

  // Smart Routing / Get All Issuer Name List
  GET_ALL_ISSUER_NAME_LIST_ACTION:
    '@smart-routing/GET_ALL_ISSUER_NAME_LIST_ACTION',
  GET_ALL_ISSUER_NAME_LIST_REQUEST:
    '@smart-routing/GET_ALL_ISSUER_NAME_LIST_REQUEST',
  GET_ALL_ISSUER_NAME_LIST_SUCCESS:
    '@smart-routing/GET_ALL_ISSUER_NAME_LIST_SUCCESS',
  GET_ALL_ISSUER_NAME_LIST_FAILURE:
    '@smart-routing/GET_ALL_ISSUER_NAME_LIST_FAILURE',
  GET_ALL_ISSUER_NAME_LIST_CLEAR:
    '@smart-routing/GET_ALL_ISSUER_NAME_LIST_CLEAR',

  // Smart Routing / Create Preference Score
  POST_CREATE_PREFERENCE_SCORE_ACTION:
    '@smart-routing/POST_CREATE_PREFERENCE_SCORE_ACTION',
  POST_CREATE_PREFERENCE_SCORE_REQUEST:
    '@smart-routing/POST_CREATE_PREFERENCE_SCORE_REQUEST',
  POST_CREATE_PREFERENCE_SCORE_SUCCESS:
    '@smart-routing/POST_CREATE_PREFERENCE_SCORE_SUCCESS',
  POST_CREATE_PREFERENCE_SCORE_FAILURE:
    '@smart-routing/POST_CREATE_PREFERENCE_SCORE_FAILURE',
  POST_CREATE_PREFERENCE_SCORE_CLEAR:
    '@smart-routing/POST_CREATE_PREFERENCE_SCORE_CLEAR',

  // Smart Routing / Delete Preference Score
  POST_DELETE_PREFERENCE_SCORE_ACTION:
    '@smart-routing/POST_DELETE_PREFERENCE_SCORE_ACTION',
  POST_DELETE_PREFERENCE_SCORE_REQUEST:
    '@smart-routing/POST_DELETE_PREFERENCE_SCORE_REQUEST',
  POST_DELETE_PREFERENCE_SCORE_SUCCESS:
    '@smart-routing/POST_DELETE_PREFERENCE_SCORE_SUCCESS',
  POST_DELETE_PREFERENCE_SCORE_FAILURE:
    '@smart-routing/POST_DELETE_PREFERENCE_SCORE_FAILURE',
  POST_DELETE_PREFERENCE_SCORE_CLEAR:
    '@smart-routing/POST_DELETE_PREFERENCE_SCORE_CLEAR',

  // Smart Routing / View Simple Routing Logic
  GET_VIEW_SIMPLE_ROUTING_LOGIC_ACTION:
    '@smart-routing/GET_VIEW_SIMPLE_ROUTING_LOGIC_ACTION',
  GET_VIEW_SIMPLE_ROUTING_LOGIC_REQUEST:
    '@smart-routing/GET_VIEW_SIMPLE_ROUTING_LOGIC_REQUEST',
  GET_VIEW_SIMPLE_ROUTING_LOGIC_SUCCESS:
    '@smart-routing/GET_VIEW_SIMPLE_ROUTING_LOGIC_SUCCESS',
  GET_VIEW_SIMPLE_ROUTING_LOGIC_FAILURE:
    '@smart-routing/GET_VIEW_SIMPLE_ROUTING_LOGIC_FAILURE',
  GET_VIEW_SIMPLE_ROUTING_LOGIC_CLEAR:
    '@smart-routing/GET_VIEW_SIMPLE_ROUTING_LOGIC_CLEAR',

  // Smart Routing / Change Gateway Status
  POST_CHANGE_GATEWAY_STATUS_ACTION:
    '@smart-routing/POST_CHANGE_GATEWAY_STATUS_ACTION',
  POST_CHANGE_GATEWAY_STATUS_REQUEST:
    '@smart-routing/POST_CHANGE_GATEWAY_STATUS_REQUEST',
  POST_CHANGE_GATEWAY_STATUS_SUCCESS:
    '@smart-routing/POST_CHANGE_GATEWAY_STATUS_SUCCESS',
  POST_CHANGE_GATEWAY_STATUS_FAILURE:
    '@smart-routing/POST_CHANGE_GATEWAY_STATUS_FAILURE',
  POST_CHANGE_GATEWAY_STATUS_CLEAR:
    '@smart-routing/POST_CHANGE_GATEWAY_STATUS_CLEAR',

  // Smart Routing / Delete Priority Logic
  DELETE_PRIORITY_LOGIC_ACTION: '@smart-routing/DELETE_PRIORITY_LOGIC_ACTION',
  DELETE_PRIORITY_LOGIC_REQUEST: '@smart-routing/DELETE_PRIORITY_LOGIC_REQUEST',
  DELETE_PRIORITY_LOGIC_SUCCESS: '@smart-routing/DELETE_PRIORITY_LOGIC_SUCCESS',
  DELETE_PRIORITY_LOGIC_FAILURE: '@smart-routing/DELETE_PRIORITY_LOGIC_FAILURE',
  DELETE_PRIORITY_LOGIC_CLEAR: '@smart-routing/DELETE_PRIORITY_LOGIC_CLEAR',

  // Settings / Get Merchent Webhook
  GET_ACTIVE_WEBHOOK_EVENTS: '@settings/GET_ACTIVE_WEBHOOK_EVENTS',
  GET_ACTIVE_WEBHOOK_EVENTS_REQUEST:
    '@settings/GET_ACTIVE_WEBHOOK_EVENTS_REQUEST',
  GET_ACTIVE_WEBHOOK_EVENTS_SUCCESS:
    '@settings/GET_ACTIVE_WEBHOOK_EVENTS_SUCCESS',
  GET_ACTIVE_WEBHOOK_EVENTS_FAILURE:
    '@settings/GET_ACTIVE_WEBHOOK_EVENTS_FAILURE',
  GET_ACTIVE_WEBHOOK_EVENTS_CLEAR: '@settings/GET_ACTIVE_WEBHOOK_EVENTS_CLEAR',

  // Settings / Get Merchent Settings
  GET_MERCHENT_SETTINGS: '@settings/GET_MERCHENT_SETTINGS',
  GET_MERCHENT_SETTINGS_REQUEST: '@settings/GET_MERCHENT_SETTINGS_REQUEST',
  GET_MERCHENT_SETTINGS_SUCCESS: '@settings/GET_MERCHENT_SETTINGS_SUCCESS',
  GET_MERCHENT_SETTINGS_FAILURE: '@settings/GET_MERCHENT_SETTINGS_FAILURE',
  GET_MERCHENT_SETTINGS_CLEAR: '@settings/GET_MERCHENT_SETTINGS_CLEAR',

  // Settings / Update Merchent General Settings
  UPDATE_MERCHENT_GENERAL_SETTINGS:
    '@settings/UPDATE_MERCHENT_GENERAL_SETTINGS',
  UPDATE_MERCHENT_GENERAL_SETTINGS_REQUEST:
    '@settings/UPDATE_MERCHENT_GENERAL_SETTINGS_REQUEST',
  UPDATE_MERCHENT_GENERAL_SETTINGS_SUCCESS:
    '@settings/UPDATE_MERCHENT_GENERAL_SETTINGS_SUCCESS',
  UPDATE_MERCHENT_GENERAL_SETTINGS_FAILURE:
    '@settings/UPDATE_MERCHENT_GENERAL_SETTINGS_FAILURE',
  UPDATE_MERCHENT_GENERAL_SETTINGS_CLEAR:
    '@settings/UPDATE_MERCHENT_GENERAL_SETTINGS_CLEAR',

  // Settings / Update Merchent Webhook
  UPDATE_MERCHENT_WEBHOOK: '@settings/UPDATE_MERCHENT_WEBHOOK',
  UPDATE_MERCHENT_WEBHOOK_REQUEST: '@settings/UPDATE_MERCHENT_WEBHOOK_REQUEST',
  UPDATE_MERCHENT_WEBHOOK_SUCCESS: '@settings/UPDATE_MERCHENT_WEBHOOK_SUCCESS',
  UPDATE_MERCHENT_WEBHOOK_FAILURE: '@settings/UPDATE_MERCHENT_WEBHOOK_FAILURE',
  UPDATE_MERCHENT_WEBHOOK_CLEAR: '@settings/UPDATE_MERCHENT_WEBHOOK_CLEAR',

  // Setting / User Management / Get Active Users
  GET_ACTIVE_USERS_LIST: '@settings/GET_ACTIVE_USERS_LIST',
  GET_ACTIVE_USERS_LIST_REQUEST: '@settings/GET_ACTIVE_USERS_LIST_REQUEST',
  GET_ACTIVE_USERS_LIST_SUCCESS: '@settings/GET_ACTIVE_USERS_LIST_SUCCESS',
  GET_ACTIVE_USERS_LIST_FAILURE: '@settings/GET_ACTIVE_USERS_LIST_FAILURE',
  GET_ACTIVE_USERS_LIST_CLEAR: '@settings/GET_ACTIVE_USERS_LIST_CLEAR',

  // Setting / User Management / Get All Roles
  GET_ALL_ROLES: '@settings/GET_ALL_ROLES',
  GET_ALL_ROLES_REQUEST: '@settings/GET_ALL_ROLES_REQUEST',
  GET_ALL_ROLES_SUCCESS: '@settings/GET_ALL_ROLES_SUCCESS',
  GET_ALL_ROLES_FAILURE: '@settings/GET_ALL_ROLES_FAILURE',
  GET_ALL_ROLES_CLEAR: '@settings/GET_ALL_ROLES_CLEAR',

  // Setting / User Management / Get All Permissions List
  GET_ALL_PERMISSIONS_LIST: '@settings/GET_ALL_PERMISSIONS_LIST',
  GET_ALL_PERMISSIONS_LIST_REQUEST:
    '@settings/GET_ALL_PERMISSIONS_LIST_REQUEST',
  GET_ALL_PERMISSIONS_LIST_SUCCESS:
    '@settings/GET_ALL_PERMISSIONS_LIST_SUCCESS',
  GET_ALL_PERMISSIONS_LIST_FAILURE:
    '@settings/GET_ALL_PERMISSIONS_LIST_FAILURE',
  GET_ALL_PERMISSIONS_LIST_CLEAR: '@settings/GET_ALL_PERMISSIONS_LIST_CLEAR',

  // Setting / User Management / Create New User
  POST_CREATE_NEW_USER: '@settings/POST_CREATE_NEW_USER',
  POST_CREATE_NEW_USER_REQUEST: '@settings/POST_CREATE_NEW_USER_REQUEST',
  POST_CREATE_NEW_USER_SUCCESS: '@settings/POST_CREATE_NEW_USER_SUCCESS',
  POST_CREATE_NEW_USER_FAILURE: '@settings/POST_CREATE_NEW_USER_FAILURE',
  POST_CREATE_NEW_USER_CLEAR: '@settings/POST_CREATE_NEW_USER_CLEAR',

  // Setting / User Management / Update New User
  POST_UPDATE_USER_DETAILS: '@settings/POST_UPDATE_USER_DETAILS',
  POST_UPDATE_USER_DETAILS_REQUEST:
    '@settings/POST_UPDATE_USER_DETAILS_REQUEST',
  POST_UPDATE_USER_DETAILS_SUCCESS:
    '@settings/POST_UPDATE_USER_DETAILS_SUCCESS',
  POST_UPDATE_USER_DETAILS_FAILURE:
    '@settings/POST_UPDATE_USER_DETAILS_FAILURE',
  POST_UPDATE_USER_DETAILS_CLEAR: '@settings/POST_UPDATE_USER_DETAILS_CLEAR',

  // Setting / User Management / Delete User
  DELETE_USER: '@settings/DELETE_USER',
  DELETE_USER_REQUEST: '@settings/DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: '@settings/DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: '@settings/DELETE_USER_FAILURE',
  DELETE_USER_CLEAR: '@settings/DELETE_USER_CLEAR',

  // Setting / User Management / Create New Role
  POST_CREATE_NEW_ROLE: '@settings/POST_CREATE_NEW_ROLE',
  POST_CREATE_NEW_ROLE_REQUEST: '@settings/POST_CREATE_NEW_ROLE_REQUEST',
  POST_CREATE_NEW_ROLE_SUCCESS: '@settings/POST_CREATE_NEW_ROLE_SUCCESS',
  POST_CREATE_NEW_ROLE_FAILURE: '@settings/POST_CREATE_NEW_ROLE_FAILURE',
  POST_CREATE_NEW_ROLE_CLEAR: '@settings/POST_CREATE_NEW_ROLE_CLEAR',

  // Setting / User Management / Resend Invitation
  POST_RESEND_INVITATION: '@settings/POST_RESEND_INVITATION',
  POST_RESEND_INVITATION_REQUEST: '@settings/POST_RESEND_INVITATION_REQUEST',
  POST_RESEND_INVITATION_SUCCESS: '@settings/POST_RESEND_INVITATION_SUCCESS',
  POST_RESEND_INVITATION_FAILURE: '@settings/POST_RESEND_INVITATION_FAILURE',
  POST_RESEND_INVITATION_CLEAR: '@settings/POST_RESEND_INVITATION_CLEAR',

  // Setting / Checkout Theme / Get Theme
  GET_CHECKOUT_THEME: '@settings/GET_CHECKOUT_THEME',
  GET_CHECKOUT_THEME_REQUEST: '@settings/GET_CHECKOUT_THEME_REQUEST',
  GET_CHECKOUT_THEME_SUCCESS: '@settings/GET_CHECKOUT_THEME_SUCCESS',
  GET_CHECKOUT_THEME_FAILURE: '@settings/GET_CHECKOUT_THEME_FAILURE',
  GET_CHECKOUT_THEME_CLEAR: '@settings/GET_CHECKOUT_THEME_CLEAR',

  // Setting / Checkout Theme / Update Theme
  POST_UPDATE_CHECKOUT_THEME: '@settings/POST_UPDATE_CHECKOUT_THEME',
  POST_UPDATE_CHECKOUT_THEME_REQUEST:
    '@settings/POST_UPDATE_CHECKOUT_THEME_REQUEST',
  POST_UPDATE_CHECKOUT_THEME_SUCCESS:
    '@settings/POST_UPDATE_CHECKOUT_THEME_SUCCESS',
  POST_UPDATE_CHECKOUT_THEME_FAILURE:
    '@settings/POST_UPDATE_CHECKOUT_THEME_FAILURE',
  POST_UPDATE_CHECKOUT_THEME_CLEAR:
    '@settings/POST_UPDATE_CHECKOUT_THEME_CLEAR',

  // Payment / Get Listing
  GET_PAYMENT_LIST: '@payment/GET_PAYMENT_LIST',
  GET_PAYMENT_LIST_REQUEST: '@payment/GET_PAYMENT_LIST_REQUEST',
  GET_PAYMENT_LIST_SUCCESS: '@payment/GET_PAYMENT_LIST_SUCCESS',
  GET_PAYMENT_LIST_FAILURE: '@payment/GET_PAYMENT_LIST_FAILURE',
  GET_PAYMENT_LIST_CLEAR: '@payment/GET_PAYMENT_LIST_CLEAR',

  // Payment / Order Details
  GET_PAYMENT_ORDER_DETAILS: '@payment/GET_PAYMENT_ORDER_DETAILS',
  GET_PAYMENT_ORDER_DETAILS_REQUEST:
    '@payment/GET_PAYMENT_ORDER_DETAILS_REQUEST',
  GET_PAYMENT_ORDER_DETAILS_SUCCESS:
    '@payment/GET_PAYMENT_ORDER_DETAILS_SUCCESS',
  GET_PAYMENT_ORDER_DETAILS_FAILURE:
    '@payment/GET_PAYMENT_ORDER_DETAILS_FAILURE',
  GET_PAYMENT_ORDER_DETAILS_CLEAR: '@payment/GET_PAYMENT_ORDER_DETAILS_CLEAR',

  GET_ALL_ORDER_STATUS_LIST: '@payment/GET_ALL_ORDER_STATUS_LIST',
  GET_ALL_ORDER_STATUS_LIST_REQUEST:
    '@payment/GET_ALL_ORDER_STATUS_LIST_REQUEST',
  GET_ALL_ORDER_STATUS_LIST_SUCCESS:
    '@payment/GET_ALL_ORDER_STATUS_LIST_SUCCESS',
  GET_ALL_ORDER_STATUS_LIST_FAILURE:
    '@payment/GET_ALL_ORDER_STATUS_LIST_FAILURE',
  GET_ALL_ORDER_STATUS_LIST_CLEAR: '@payment/GET_ALL_ORDER_STATUS_LIST_CLEAR',

  GET_ALL_GATEWAYS_LIST: '@payment/GET_ALL_GATEWAYS_LIST',
  GET_ALL_GATEWAYS_LIST_REQUEST: '@payment/GET_ALL_GATEWAYS_LIST_REQUEST',
  GET_ALL_GATEWAYS_LIST_SUCCESS: '@payment/GET_ALL_GATEWAYS_LIST_SUCCESS',
  GET_ALL_GATEWAYS_LIST_FAILURE: '@payment/GET_ALL_GATEWAYS_LIST_FAILURE',
  GET_ALL_GATEWAYS_LIST_CLEAR: '@payment/GET_ALL_GATEWAYS_LIST_CLEAR',

  // Refund / Get Listing
  GET_REFUND_LIST: '@refund/GET_REFUND_LIST',
  GET_REFUND_LIST_REQUEST: '@refund/GET_REFUND_LIST_REQUEST',
  GET_REFUND_LIST_SUCCESS: '@refund/GET_REFUND_LIST_SUCCESS',
  GET_REFUND_LIST_FAILURE: '@refund/GET_REFUND_LIST_FAILURE',
  GET_REFUND_LIST_CLEAR: '@refund/GET_REFUND_LIST_CLEAR',

  // Refund / create Refund
  POST_CREATE_REFUND: '@refund/POST_CREATE_REFUND',
  POST_CREATE_REFUND_REQUEST: '@refund/POST_CREATE_REFUND_REQUEST',
  POST_CREATE_REFUND_SUCCESS: '@refund/POST_CREATE_REFUND_SUCCESS',
  POST_CREATE_REFUND_FAILURE: '@refund/POST_CREATE_REFUND_FAILURE',
  POST_CREATE_REFUND_CLEAR: '@refund/POST_CREATE_REFUND_CLEAR',
  // Refund / Get Bulk Upload History Listing
  GET_REFUND_BULK_UPLOAD_HISTORY_LIST:
    '@refund/GET_REFUND_BULK_UPLOAD_HISTORY_LIST',
  GET_REFUND_BULK_UPLOAD_HISTORY_LIST_REQUEST:
    '@refund/GET_REFUND_BULK_UPLOAD_HISTORY_LIST_REQUEST',
  GET_REFUND_BULK_UPLOAD_HISTORY_LIST_SUCCESS:
    '@refund/GET_REFUND_BULK_UPLOAD_HISTORY_LIST_SUCCESS',
  GET_REFUND_BULK_UPLOAD_HISTORY_LIST_FAILURE:
    '@refund/GET_REFUND_BULK_UPLOAD_HISTORY_LIST_FAILURE',
  GET_REFUND_BULK_UPLOAD_HISTORY_LIST_CLEAR:
    '@refund/GET_REFUND_BULK_UPLOAD_HISTORY_LIST_CLEAR',

  // Overview/ Get Today Transactions Data
  GET_TODAY_TRANSACTIONS_DATA: '@overview/GET_TODAY_TRANSACTIONS_DATA',
  GET_TODAY_TRANSACTIONS_DATA_REQUEST:
    '@overview/GET_TODAY_TRANSACTIONS_DATA_REQUEST',
  GET_TODAY_TRANSACTIONS_DATA_SUCCESS:
    '@overview/GET_TODAY_TRANSACTIONS_DATA_SUCCESS',
  GET_TODAY_TRANSACTIONS_DATA_FAILURE:
    '@overview/GET_TODAY_TRANSACTIONS_DATA_FAILURE',
  GET_TODAY_TRANSACTIONS_DATA_CLEAR:
    '@overview/GET_TODAY_TRANSACTIONS_DATA_CLEAR',

  // Overview/ Get Today Transactions Data
  GET_OVERVIEW_DATA: '@overview/GET_OVERVIEW_DATA',
  GET_OVERVIEW_DATA_REQUEST: '@overview/GET_OVERVIEW_DATA_REQUEST',
  GET_OVERVIEW_DATA_SUCCESS: '@overview/GET_OVERVIEW_DATA_SUCCESS',
  GET_OVERVIEW_DATA_FAILURE: '@overview/GET_OVERVIEW_DATA_FAILURE',
  GET_OVERVIEW_DATA_CLEAR: '@overview/GET_OVERVIEW_DATA_CLEAR',

  // Sidebar
  UPDATE_SIDEBAR_VIEW: '@sidebar/UPDATE_SIDEBAR_VIEW',

  // Payment Links / Get Listing
  GET_PAYMENT_LINKS_LIST: '@payment-link/GET_PAYMENT_LINKS_LIST',
  GET_PAYMENT_LINKS_LIST_REQUEST:
    '@payment-link/GET_PAYMENT_LINKS_LIST_REQUEST',
  GET_PAYMENT_LINKS_LIST_SUCCESS:
    '@payment-link/GET_PAYMENT_LINKS_LIST_SUCCESS',
  GET_PAYMENT_LINKS_LIST_FAILURE:
    '@payment-link/GET_PAYMENT_LINKS_LIST_FAILURE',
  GET_PAYMENT_LINKS_LIST_CLEAR: '@payment-link/GET_PAYMENT_LINKS_LIST_CLEAR',

  // Payment Links / Create Payment Link
  POST_CREATE_PAYMENT_LINK: '@payment-link/POST_CREATE_PAYMENT_LINK',
  POST_CREATE_PAYMENT_LINK_REQUEST:
    '@payment-link/POST_CREATE_PAYMENT_LINK_REQUEST',
  POST_CREATE_PAYMENT_LINK_SUCCESS:
    '@payment-link/POST_CREATE_PAYMENT_LINK_SUCCESS',
  POST_CREATE_PAYMENT_LINK_FAILURE:
    '@payment-link/POST_CREATE_PAYMENT_LINK_FAILURE',
  POST_CREATE_PAYMENT_LINK_CLEAR:
    '@payment-link/POST_CREATE_PAYMENT_LINK_CLEAR',

  // Merchant Listing
  GET_MERCHANT_LIST: '@merchant-listing/GET_MERCHANT_LIST',
  GET_MERCHANT_LIST_REQUEST: '@merchant-listing/GET_MERCHANT_LIST_REQUEST',
  GET_MERCHANT_LIST_SUCCESS: '@merchant-listing/GET_MERCHANT_LIST_SUCCESS',
  GET_MERCHANT_LIST_FAILURE: '@merchant-listing/GET_MERCHANT_LIST_FAILURE',
  GET_MERCHANT_LIST_CLEAR: '@merchant-listing/GET_MERCHANT_LIST_CLEAR',

  // Admin Custom Routing List
  GET_ADMIN_CUSTOM_ROUTING_LIST:
    '@admin-routing-list/GET_ADMIN_CUSTOM_ROUTING_LIST',
  GET_ADMIN_CUSTOM_ROUTING_LIST_REQUEST:
    '@admin-routing-list/GET_ADMIN_CUSTOM_ROUTING_LIST_REQUEST',
  GET_ADMIN_CUSTOM_ROUTING_LIST_SUCCESS:
    '@admin-routing-list/GET_ADMIN_CUSTOM_ROUTING_LIST_SUCCESS',
  GET_ADMIN_CUSTOM_ROUTING_LIST_FAILURE:
    '@admin-routing-list/GET_ADMIN_CUSTOM_ROUTING_LIST_FAILURE',
  GET_ADMIN_CUSTOM_ROUTING_LIST_CLEAR:
    '@admin-routing-list/GET_ADMIN_CUSTOM_ROUTING_LIST_CLEAR',

  // Get Admin Custom Routing Logic
  GET_ADMIN_PRIORITY_LOGIC: '@admin-priority-logic/GET_ADMIN_PRIORITY_LOGIC',
  GET_ADMIN_PRIORITY_LOGIC_REQUEST:
    '@admin-priority-logic/GET_ADMIN_PRIORITY_LOGIC_REQUEST',
  GET_ADMIN_PRIORITY_LOGIC_SUCCESS:
    '@admin-priority-logic/GET_ADMIN_PRIORITY_LOGIC_SUCCESS',
  GET_ADMIN_PRIORITY_LOGIC_FAILURE:
    '@admin-priority-logic/GET_ADMIN_PRIORITY_LOGIC_FAILURE',
  GET_ADMIN_PRIORITY_LOGIC_CLEAR:
    '@admin-priority-logic/GET_ADMIN_PRIORITY_LOGIC_CLEAR',

  // Approve Or Reject Routing Logic
  PUT_APPROVE_OR_REJECT_LOGIC:
    '@admin-approved-or-reject/PUT_APPROVE_OR_REJECT_LOGIC',
  PUT_APPROVE_OR_REJECT_LOGIC_REQUEST:
    '@admin-approved-or-reject/PUT_APPROVE_OR_REJECT_LOGIC_REQUEST',
  PUT_APPROVE_OR_REJECT_LOGIC_SUCCESS:
    '@admin-approved-or-reject/PUT_APPROVE_OR_REJECT_LOGIC_SUCCESS',
  PUT_APPROVE_OR_REJECT_LOGIC_FAILURE:
    '@admin-approved-or-reject/PUT_APPROVE_OR_REJECT_LOGIC_FAILURE',
  PUT_APPROVE_OR_REJECT_LOGIC_CLEAR:
    '@admin-approved-or-reject/PUT_APPROVE_OR_REJECT_LOGIC_CLEAR',

  // Update Admin Routing Logic
  UPDATE_ADMIN_PRIORITY_LOGIC:
    '@admin-routing-logic/UPDATE_ADMIN_PRIORITY_LOGIC',
  UPDATE_ADMIN_PRIORITY_LOGIC_REQUEST:
    '@admin-routing-logic/UPDATE_ADMIN_PRIORITY_LOGIC_REQUEST',
  UPDATE_ADMIN_PRIORITY_LOGIC_SUCCESS:
    '@admin-routing-logic/UPDATE_ADMIN_PRIORITY_LOGIC_SUCCESS',
  UPDATE_ADMIN_PRIORITY_LOGIC_FAILURE:
    '@admin-routing-logic/UPDATE_ADMIN_PRIORITY_LOGIC_FAILURE',
  UPDATE_ADMIN_PRIORITY_LOGIC_CLEAR:
    '@admin-routing-logic/UPDATE_ADMIN_PRIORITY_LOGIC_CLEAR',

  // Admin Custom Routing List
  GET_ADMIN_CUSTOM_ROUTING_AUTO_SUGGEST_LIST:
    '@admin-routing-list/GET_ADMIN_CUSTOM_ROUTING_AUTO_SUGGEST_LIST',
  GET_ADMIN_CUSTOM_ROUTING_AUTO_SUGGEST_LIST_REQUEST:
    '@admin-routing-list/GET_ADMIN_CUSTOM_ROUTING_AUTO_SUGGEST_LIST_REQUEST',
  GET_ADMIN_CUSTOM_ROUTING_AUTO_SUGGEST_LIST_SUCCESS:
    '@admin-routing-list/GET_ADMIN_CUSTOM_ROUTING_AUTO_SUGGEST_LIST_SUCCESS',
  GET_ADMIN_CUSTOM_ROUTING_AUTO_SUGGEST_LIST_FAILURE:
    '@admin-routing-list/GET_ADMIN_CUSTOM_ROUTING_AUTO_SUGGEST_LIST_FAILURE',
  GET_ADMIN_CUSTOM_ROUTING_AUTO_SUGGEST_LIST_CLEAR:
    '@admin-routing-list/GET_ADMIN_CUSTOM_ROUTING_AUTO_SUGGEST_LIST_CLEAR',

  // Update Merchant TRM Status
  PUT_UPDATE_MERCHANT_TRM_STATUS_ACTION:
    '@admin/PUT_UPDATE_MERCHANT_TRM_STATUS_ACTION',
  PUT_UPDATE_MERCHANT_TRM_STATUS_REQUEST:
    '@admin/PUT_UPDATE_MERCHANT_TRM_STATUS_REQUEST',
  PUT_UPDATE_MERCHANT_TRM_STATUS_SUCCESS:
    '@admin/PUT_UPDATE_MERCHANT_TRM_STATUS_SUCCESS',
  PUT_UPDATE_MERCHANT_TRM_STATUS_FAILURE:
    '@admin/PUT_UPDATE_MERCHANT_TRM_STATUS_FAILURE',
  PUT_UPDATE_MERCHANT_TRM_STATUS_CLEAR:
    '@admin/PUT_UPDATE_MERCHANT_TRM_STATUS_CLEAR',

  // Merchant Search
  MERCHANT_SEARCH: '@merchant-listing/MERCHANT_SEARCH',
  MERCHANT_SEARCH_REQUEST: '@merchant-listing/MERCHANT_SEARCH_REQUEST',
  MERCHANT_SEARCH_SUCCESS: '@merchant-listing/MERCHANT_SEARCH_SUCCESS',
  MERCHANT_SEARCH_FAILURE: '@merchant-listing/MERCHANT_SEARCH_FAILURE',
  MERCHANT_SEARCH_CLEAR: '@merchant-listing/MERCHANT_SEARCH_CLEAR',

  // Captcha
  CLIENT_SECRET_KEY_ACTION: '@Captcha/CLIENT_SECRET_KEY_ACTION',
  CLIENT_SECRET_KEY_REQUEST: '@Captcha/CLIENT_SECRET_KEY_REQUEST',
  CLIENT_SECRET_KEY_SUCCESS: '@Captcha/CLIENT_SECRET_KEY_SUCCESS',
  CLIENT_SECRET_KEY_FAILURE: '@Captcha/CLIENT_SECRET_KEY_FAILURE',
  CLIENT_SECRET_KEY_CLEAR: '@Captcha/CLIENT_SECRET_KEY_CLEAR',

  // Verify Captcha
  CAPTCHA_VERIFY_ACTION: '@Captcha/CAPTCHA_VERIFY_ACTION',
  CAPTCHA_VERIFY_REQUEST: '@Captcha/CAPTCHA_VERIFY_REQUEST',
  CAPTCHA_VERIFY_SUCCESS: '@Captcha/CAPTCHA_VERIFY_SUCCESS',
  CAPTCHA_VERIFY_FAILURE: '@Captcha/CAPTCHA_VERIFY_FAILURE',
  CAPTCHA_VERIFY_CLEAR: '@Captcha/CAPTCHA_VERIFY_CLEAR',

  // Payment Link Bulk Upload History
  GET_PAYMENT_LINK_BULK_UPLOAD_HISTORY_ACTION:
    '@payment-link/GET_PAYMENT_LINK_BULK_UPLOAD_HISTORY_ACTION',
  GET_PAYMENT_LINK_BULK_UPLOAD_HISTORY_REQUEST:
    '@payment-link/GET_PAYMENT_LINK_BULK_UPLOAD_HISTORY_REQUEST',
  GET_PAYMENT_LINK_BULK_UPLOAD_HISTORY_SUCCESS:
    '@payment-link/GET_PAYMENT_LINK_BULK_UPLOAD_HISTORY_SUCCESS',
  GET_PAYMENT_LINK_BULK_UPLOAD_HISTORY_FAILURE:
    '@payment-link/GET_PAYMENT_LINK_BULK_UPLOAD_HISTORY_FAILURE',
  GET_PAYMENT_LINK_BULK_UPLOAD_HISTORY_CLEAR:
    '@payment-link/GET_PAYMENT_LINK_BULK_UPLOAD_HISTORY_CLEAR',

  // Payment Link Status Code
  GET_PAYMENT_LINK_STATUS_CODE_ACTION:
    '@payment-link/GET_PAYMENT_LINK_STATUS_CODE_ACTION',
  GET_PAYMENT_LINK_STATUS_CODE_REQUEST:
    '@payment-link/GET_PAYMENT_LINK_STATUS_CODE_REQUEST',
  GET_PAYMENT_LINK_STATUS_CODE_SUCCESS:
    '@payment-link/GET_PAYMENT_LINK_STATUS_CODE_SUCCESS',
  GET_PAYMENT_LINK_STATUS_CODE_FAILURE:
    '@payment-link/GET_PAYMENT_LINK_STATUS_CODE_FAILURE',
  GET_PAYMENT_LINK_STATUS_CODE_CLEAR:
    '@payment-link/GET_PAYMENT_LINK_STATUS_CODE_CLEAR',

  // refund
  GET_ALL_REFUND_STATUS_LIST: '@refund/GET_ALL_REFUND_STATUS_LIST',
  GET_ALL_REFUND_STATUS_LIST_REQUEST:
    '@refund/GET_ALL_REFUND_STATUS_LIST_REQUEST',
  GET_ALL_REFUND_STATUS_LIST_SUCCESS:
    '@refund/GET_ALL_REFUND_STATUS_LIST_SUCCESS',
  GET_ALL_REFUND_STATUS_LIST_FAILURE:
    '@refund/GET_ALL_REFUND_STATUS_LIST_FAILURE',
  GET_ALL_REFUND_STATUS_LIST_CLEAR: '@refund/GET_ALL_REFUND_STATUS_LIST_CLEAR',

  // Download CSV
  GET_DOWNLOAD_CSV_ACTION: '@file-download/GET_DOWNLOAD_CSV_ACTION',
  GET_DOWNLOAD_CSV_REQUEST: '@file-download/GET_DOWNLOAD_CSV_REQUEST',

  // get trm login link
  GET_TRM_REDIRECT_URL: '@refund/GET_TRM_REDIRECT_URL',
  GET_TRM_REDIRECT_URL_REQUEST: '@refund/GET_TRM_REDIRECT_URL_REQUEST',
  GET_TRM_REDIRECT_URL_SUCCESS: '@refund/GET_TRM_REDIRECT_URL_SUCCESS',
  GET_TRM_REDIRECT_URL_FAILURE: '@refund/GET_TRM_REDIRECT_URL_FAILURE',
  GET_TRM_REDIRECT_URL_CLEAR: '@refund/GET_TRM_REDIRECT_URL_CLEAR',

  // validate register token url
  GET_VALIDATE_INVITATION_URL: '@register/GET_VALIDATE_INVITATION_URL',
  GET_VALIDATE_INVITATION_URL_REQUEST:
    '@register/GET_VALIDATE_INVITATION_URL_REQUEST',
  GET_VALIDATE_INVITATION_URL_SUCCESS:
    '@register/GET_VALIDATE_INVITATION_URL_SUCCESS',
  GET_VALIDATE_INVITATION_URL_FAILURE:
    '@register/GET_VALIDATE_INVITATION_URL_FAILURE',
  GET_VALIDATE_INVITATION_URL_CLEAR:
    '@register/GET_VALIDATE_INVITATION_URL_CLEAR',

  // login OTP timer
  SET_IS_TIMER_COMPTLETE: 'SET_IS_TIMER_COMPTLETE',

  // Add new beneficiary
  POST_ADD_NEW_BENEFICIARY: '@payouts/POST_ADD_NEW_BENEFICIARY',
  POST_ADD_NEW_BENEFICIARY_REQUEST: '@payouts/POST_ADD_NEW_BENEFICIARY_REQUEST',
  POST_ADD_NEW_BENEFICIARY_SUCCESS: '@payouts/POST_ADD_NEW_BENEFICIARY_SUCCESS',
  POST_ADD_NEW_BENEFICIARY_FAILURE: '@payouts/POST_ADD_NEW_BENEFICIARY_FAILURE',
  POST_ADD_NEW_BENEFICIARY_CLEAR: '@payouts/POST_ADD_NEW_BENEFICIARY_CLEAR',

  // get beneficiary list
  GET_BENEFICIARY_LIST: '@payouts/GET_BENEFICIARY_LIST',
  GET_BENEFICIARY_LIST_REQUEST: '@payouts/GET_BENEFICIARY_LIST_REQUEST',
  GET_BENEFICIARY_LIST_SUCCESS: '@payouts/GET_BENEFICIARY_LIST_SUCCESS',
  GET_BENEFICIARY_LIST_FAILURE: '@payouts/GET_BENEFICIARY_LIST_FAILURE',
  GET_BENEFICIARY_LIST_CLEAR: '@payouts/GET_BENEFICIARY_LIST_CLEAR',

  // approve beneficiary
  POST_APPROVE_BENEFICIARY: '@payouts/POST_APPROVE_BENEFICIARY',
  POST_APPROVE_BENEFICIARY_REQUEST: '@payouts/POST_APPROVE_BENEFICIARY_REQUEST',
  POST_APPROVE_BENEFICIARY_SUCCESS: '@payouts/POST_APPROVE_BENEFICIARY_SUCCESS',
  POST_APPROVE_BENEFICIARY_FAILURE: '@payouts/POST_APPROVE_BENEFICIARY_FAILURE',
  POST_APPROVE_BENEFICIARY_CLEAR: '@payouts/POST_APPROVE_BENEFICIARY_CLEAR',

  // reject beneficiary
  POST_REJECT_BENEFICIARY: '@payouts/POST_REJECT_BENEFICIARY',
  POST_REJECT_BENEFICIARY_REQUEST: '@payouts/POST_REJECT_BENEFICIARY_REQUEST',
  POST_REJECT_BENEFICIARY_SUCCESS: '@payouts/POST_REJECT_BENEFICIARY_SUCCESS',
  POST_REJECT_BENEFICIARY_FAILURE: '@payouts/POST_REJECT_BENEFICIARY_FAILURE',
  POST_REJECT_BENEFICIARY_CLEAR: '@payouts/POST_REJECT_BENEFICIARY_CLEAR',

  // deactivate beneficiary
  PUT_DEACTIVATE_BENEFICIARY: '@payouts/PUT_DEACTIVATE_BENEFICIARY',
  PUT_DEACTIVATE_BENEFICIARY_REQUEST:
    '@payouts/PUT_DEACTIVATE_BENEFICIARY_REQUEST',
  PUT_DEACTIVATE_BENEFICIARY_SUCCESS:
    '@payouts/PUT_DEACTIVATE_BENEFICIARY_SUCCESS',
  PUT_DEACTIVATE_BENEFICIARY_FAILURE:
    '@payouts/PUT_DEACTIVATE_BENEFICIARY_FAILURE',
  PUT_DEACTIVATE_BENEFICIARY_CLEAR: '@payouts/PUT_DEACTIVATE_BENEFICIARY_CLEAR',

  // get payouts list
  GET_BENEFICIARY_BY_BENEFICIARY_CODE:
    '@payouts/GET_BENEFICIARY_BY_BENEFICIARY_CODE',
  GET_BENEFICIARY_BY_BENEFICIARY_CODE_REQUEST:
    '@payouts/GET_BENEFICIARY_BY_BENEFICIARY_CODE_REQUEST',
  GET_BENEFICIARY_BY_BENEFICIARY_CODE_SUCCESS:
    '@payouts/GET_BENEFICIARY_BY_BENEFICIARY_CODE_SUCCESS',
  GET_BENEFICIARY_BY_BENEFICIARY_CODE_FAILURE:
    '@payouts/GET_BENEFICIARY_BY_BENEFICIARY_CODE_FAILURE',
  GET_BENEFICIARY_BY_BENEFICIARY_CODE_CLEAR:
    '@payouts/GET_BENEFICIARY_BY_BENEFICIARY_CODE_CLEAR',

  // get payouts list
  GET_INDIVIDUAL_PAYOUTS_LIST: '@payouts/GET_INDIVIDUAL_PAYOUTS_LIST',
  GET_INDIVIDUAL_PAYOUTS_LIST_REQUEST:
    '@payouts/GET_INDIVIDUAL_PAYOUTS_LIST_REQUEST',
  GET_INDIVIDUAL_PAYOUTS_LIST_SUCCESS:
    '@payouts/GET_INDIVIDUAL_PAYOUTS_LIST_SUCCESS',
  GET_INDIVIDUAL_PAYOUTS_LIST_FAILURE:
    '@payouts/GET_INDIVIDUAL_PAYOUTS_LIST_FAILURE',
  GET_INDIVIDUAL_PAYOUTS_LIST_CLEAR:
    '@payouts/GET_INDIVIDUAL_PAYOUTS_LIST_CLEAR',

  // post new individual payout
  POST_ADD_INDIVIDUAL_PAYOUT: '@payouts/POST_ADD_INDIVIDUAL_PAYOUT',
  POST_ADD_INDIVIDUAL_PAYOUT_REQUEST:
    '@payouts/POST_ADD_INDIVIDUAL_PAYOUT_REQUEST',
  POST_ADD_INDIVIDUAL_PAYOUT_SUCCESS:
    '@payouts/POST_ADD_INDIVIDUAL_PAYOUT_SUCCESS',
  POST_ADD_INDIVIDUAL_PAYOUT_FAILURE:
    '@payouts/POST_ADD_INDIVIDUAL_PAYOUT_FAILURE',
  POST_ADD_INDIVIDUAL_PAYOUT_CLEAR: '@payouts/POST_ADD_INDIVIDUAL_PAYOUT_CLEAR',

  // approve payout
  POST_APPROVE_INDIVIDUAL_PAYOUT: '@payouts/POST_APPROVE_INDIVIDUAL_PAYOUT',
  POST_APPROVE_INDIVIDUAL_PAYOUT_REQUEST:
    '@payouts/POST_APPROVE_INDIVIDUAL_PAYOUT_REQUEST',
  POST_APPROVE_INDIVIDUAL_PAYOUT_SUCCESS:
    '@payouts/POST_APPROVE_INDIVIDUAL_PAYOUT_SUCCESS',
  POST_APPROVE_INDIVIDUAL_PAYOUT_FAILURE:
    '@payouts/POST_APPROVE_INDIVIDUAL_PAYOUT_FAILURE',
  POST_APPROVE_INDIVIDUAL_PAYOUT_CLEAR:
    '@payouts/POST_APPROVE_INDIVIDUAL_PAYOUT_CLEAR',

  // reject payout
  POST_REJECT_INDIVIDUAL_PAYOUT: '@payouts/POST_REJECT_INDIVIDUAL_PAYOUT',
  POST_REJECT_INDIVIDUAL_PAYOUT_REQUEST:
    '@payouts/POST_REJECT_INDIVIDUAL_PAYOUT_REQUEST',
  POST_REJECT_INDIVIDUAL_PAYOUT_SUCCESS:
    '@payouts/POST_REJECT_INDIVIDUAL_PAYOUT_SUCCESS',
  POST_REJECT_INDIVIDUAL_PAYOUT_FAILURE:
    '@payouts/POST_REJECT_INDIVIDUAL_PAYOUT_FAILURE',
  POST_REJECT_INDIVIDUAL_PAYOUT_CLEAR:
    '@payouts/POST_REJECT_INDIVIDUAL_PAYOUT_CLEAR',

  // get bulk payout list
  GET_BULK_PAYOUT_LIST: '@payouts/GET_BULK_PAYOUT_LIST',
  GET_BULK_PAYOUT_LIST_REQUEST: '@payouts/GET_BULK_PAYOUT_LIST_REQUEST',
  GET_BULK_PAYOUT_LIST_SUCCESS: '@payouts/GET_BULK_PAYOUT_LIST_SUCCESS',
  GET_BULK_PAYOUT_LIST_FAILURE: '@payouts/GET_BULK_PAYOUT_LIST_FAILURE',
  GET_BULK_PAYOUT_LIST_CLEAR: '@payouts/GET_BULK_PAYOUT_LIST_CLEAR',
  // update payout module status
  PUT_UPDATE_PAYOUT_MODULE_STATUS: '@payouts/PUT_UPDATE_PAYOUT_MODULE_STATUS',
  PUT_UPDATE_PAYOUT_MODULE_STATUS_REQUEST:
    '@payouts/PUT_UPDATE_PAYOUT_MODULE_STATUS_REQUEST',
  PUT_UPDATE_PAYOUT_MODULE_STATUS_SUCCESS:
    '@payouts/PUT_UPDATE_PAYOUT_MODULE_STATUS_SUCCESS',
  PUT_UPDATE_PAYOUT_MODULE_STATUS_FAILURE:
    '@payouts/PUT_UPDATE_PAYOUT_MODULE_STATUS_FAILURE',
  PUT_UPDATE_PAYOUT_MODULE_STATUS_CLEAR:
    '@payouts/PUT_UPDATE_PAYOUT_MODULE_STATUS_CLEAR',

  // cancel approved payout
  POST_CANCEL_APPROVED_INDIVIDUAL_PAYOUT:
    '@payouts/POST_CANCEL_APPROVED_INDIVIDUAL_PAYOUT',
  POST_CANCEL_APPROVED_INDIVIDUAL_PAYOUT_REQUEST:
    '@payouts/POST_CANCEL_APPROVED_INDIVIDUAL_PAYOUT_REQUEST',
  POST_CANCEL_APPROVED_INDIVIDUAL_PAYOUT_SUCCESS:
    '@payouts/POST_CANCEL_APPROVED_INDIVIDUAL_PAYOUT_SUCCESS',
  POST_CANCEL_APPROVED_INDIVIDUAL_PAYOUT_FAILURE:
    '@payouts/POST_CANCEL_APPROVED_INDIVIDUAL_PAYOUT_FAILURE',
  POST_CANCEL_APPROVED_INDIVIDUAL_PAYOUT_CLEAR:
    '@payouts/POST_CANCEL_APPROVED_INDIVIDUAL_PAYOUT_CLEAR',

  // get payout overview pending summary
  GET_PAYOUT_OVERVIEW_PENDING_SUMMARY:
    '@payouts/GET_PAYOUT_OVERVIEW_PENDING_SUMMARY',
  GET_PAYOUT_OVERVIEW_PENDING_SUMMARY_REQUEST:
    '@payouts/GET_PAYOUT_OVERVIEW_PENDING_SUMMARY_REQUEST',
  GET_PAYOUT_OVERVIEW_PENDING_SUMMARY_SUCCESS:
    '@payouts/GET_PAYOUT_OVERVIEW_PENDING_SUMMARY_SUCCESS',
  GET_PAYOUT_OVERVIEW_PENDING_SUMMARY_FAILURE:
    '@payouts/GET_PAYOUT_OVERVIEW_PENDING_SUMMARY_FAILURE',

  // get payout overview status summary
  GET_PAYOUT_OVERVIEW_STATUS_SUMMARY:
    '@payouts/GET_PAYOUT_OVERVIEW_STATUS_SUMMARY',
  GET_PAYOUT_OVERVIEW_STATUS_SUMMARY_REQUEST:
    '@payouts/GET_PAYOUT_OVERVIEW_STATUS_SUMMARY_REQUEST',
  GET_PAYOUT_OVERVIEW_STATUS_SUMMARY_SUCCESS:
    '@payouts/GET_PAYOUT_OVERVIEW_STATUS_SUMMARY_SUCCESS',
  GET_PAYOUT_OVERVIEW_STATUS_SUMMARY_FAILURE:
    '@payouts/GET_PAYOUT_OVERVIEW_STATUS_SUMMARY_FAILURE',

  // get payout overview transaction summary
  GET_PAYOUT_OVERVIEW_TRANSACTION_SUMMARY:
    '@payouts/GET_PAYOUT_OVERVIEW_TRANSACTION_SUMMARY',
  GET_PAYOUT_OVERVIEW_TRANSACTION_SUMMARY_REQUEST:
    '@payouts/GET_PAYOUT_OVERVIEW_TRANSACTION_SUMMARY_REQUEST',
  GET_PAYOUT_OVERVIEW_TRANSACTION_SUMMARY_SUCCESS:
    '@payouts/GET_PAYOUT_OVERVIEW_TRANSACTION_SUMMARY_SUCCESS',
  GET_PAYOUT_OVERVIEW_TRANSACTION_SUMMARY_FAILURE:
    '@payouts/GET_PAYOUT_OVERVIEW_TRANSACTION_SUMMARY_FAILURE',

  // clear payout overview error state
  CLEAR_PAYOUT_OVERVIEW_ERROR_STATE:
    '@payouts/CLEAR_PAYOUT_OVERVIEW_ERROR_STATE',

  // get payout balance
  GET_PAYOUT_ACCOUNT_BALANCE: '@payouts/GET_PAYOUT_ACCOUNT_BALANCE',
  GET_PAYOUT_ACCOUNT_BALANCE_REQUEST:
    '@payouts/GET_PAYOUT_ACCOUNT_BALANCE_REQUEST',
  GET_PAYOUT_ACCOUNT_BALANCE_SUCCESS:
    '@payouts/GET_PAYOUT_ACCOUNT_BALANCE_SUCCESS',
  GET_PAYOUT_ACCOUNT_BALANCE_FAILURE:
    '@payouts/GET_PAYOUT_ACCOUNT_BALANCE_FAILURE',
  GET_PAYOUT_ACCOUNT_BALANCE_CLEAR: '@payouts/GET_PAYOUT_ACCOUNT_BALANCE_CLEAR',

  // get remitter accounts list
  GET_PAYOUT_REMITTER_ACCOUNTS_LIST:
    '@payouts/GET_PAYOUT_REMITTER_ACCOUNTS_LIST',
  GET_PAYOUT_REMITTER_ACCOUNTS_LIST_REQUEST:
    '@payouts/GET_PAYOUT_REMITTER_ACCOUNTS_LIST_REQUEST',
  GET_PAYOUT_REMITTER_ACCOUNTS_LIST_SUCCESS:
    '@payouts/GET_PAYOUT_REMITTER_ACCOUNTS_LIST_SUCCESS',
  GET_PAYOUT_REMITTER_ACCOUNTS_LIST_FAILURE:
    '@payouts/GET_PAYOUT_REMITTER_ACCOUNTS_LIST_FAILURE',
  GET_PAYOUT_REMITTER_ACCOUNTS_LIST_CLEAR:
    '@payouts/GET_PAYOUT_REMITTER_ACCOUNTS_LIST_CLEAR',

  // post add remitter account
  POST_ADD_PAYOUT_REMITTER_ACCOUNT: '@payouts/POST_ADD_PAYOUT_REMITTER_ACCOUNT',
  POST_ADD_PAYOUT_REMITTER_ACCOUNT_REQUEST:
    '@payouts/POST_ADD_PAYOUT_REMITTER_ACCOUNT_REQUEST',
  POST_ADD_PAYOUT_REMITTER_ACCOUNT_SUCCESS:
    '@payouts/POST_ADD_PAYOUT_REMITTER_ACCOUNT_SUCCESS',
  POST_ADD_PAYOUT_REMITTER_ACCOUNT_FAILURE:
    '@payouts/POST_ADD_PAYOUT_REMITTER_ACCOUNT_FAILURE',
  POST_ADD_PAYOUT_REMITTER_ACCOUNT_CLEAR:
    '@payouts/POST_ADD_PAYOUT_REMITTER_ACCOUNT_CLEAR',

  // post add remitter account
  POST_UPDATE_PAYOUT_REMITTER_ACCOUNT:
    '@payouts/POST_UPDATE_PAYOUT_REMITTER_ACCOUNT',
  POST_UPDATE_PAYOUT_REMITTER_ACCOUNT_REQUEST:
    '@payouts/POST_UPDATE_PAYOUT_REMITTER_ACCOUNT_REQUEST',
  POST_UPDATE_PAYOUT_REMITTER_ACCOUNT_SUCCESS:
    '@payouts/POST_UPDATE_PAYOUT_REMITTER_ACCOUNT_SUCCESS',
  POST_UPDATE_PAYOUT_REMITTER_ACCOUNT_FAILURE:
    '@payouts/POST_UPDATE_PAYOUT_REMITTER_ACCOUNT_FAILURE',
  POST_UPDATE_PAYOUT_REMITTER_ACCOUNT_CLEAR:
    '@payouts/POST_UPDATE_PAYOUT_REMITTER_ACCOUNT_CLEAR',

  // get payout bank list
  GET_PAYOUT_BANK_LIST: '@payouts/GET_PAYOUT_BANK_LIST',
  GET_PAYOUT_BANK_LIST_REQUEST: '@payouts/GET_PAYOUT_BANK_LIST_REQUEST',
  GET_PAYOUT_BANK_LIST_SUCCESS: '@payouts/GET_PAYOUT_BANK_LIST_SUCCESS',
  GET_PAYOUT_BANK_LIST_FAILURE: '@payouts/GET_PAYOUT_BANK_LIST_FAILURE',
  GET_PAYOUT_BANK_LIST_CLEAR: '@payouts/GET_PAYOUT_BANK_LIST_CLEAR',

  // get payout merchant kyc entity types
  GET_MERCHANT_KYC_ENTITY_TYPES_LIST:
    '@payouts/GET_MERCHANT_KYC_ENTITY_TYPES_LIST',
  GET_MERCHANT_KYC_ENTITY_TYPES_LIST_REQUEST:
    '@payouts/GET_MERCHANT_KYC_ENTITY_TYPES_LIST_REQUEST',
  GET_MERCHANT_KYC_ENTITY_TYPES_LIST_SUCCESS:
    '@payouts/GET_MERCHANT_KYC_ENTITY_TYPES_LIST_SUCCESS',
  GET_MERCHANT_KYC_ENTITY_TYPES_LIST_FAILURE:
    '@payouts/GET_MERCHANT_KYC_ENTITY_TYPES_LIST_FAILURE',
  GET_MERCHANT_KYC_ENTITY_TYPES_LIST_CLEAR:
    '@payouts/GET_MERCHANT_KYC_ENTITY_TYPES_LIST_CLEAR',

  // get merchant kyc details
  GET_MERCHANT_KYC_DETAILS: '@payouts/GET_MERCHANT_KYC_DETAILS',
  GET_MERCHANT_KYC_DETAILS_REQUEST: '@payouts/GET_MERCHANT_KYC_DETAILS_REQUEST',
  GET_MERCHANT_KYC_DETAILS_SUCCESS: '@payouts/GET_MERCHANT_KYC_DETAILS_SUCCESS',
  GET_MERCHANT_KYC_DETAILS_FAILURE: '@payouts/GET_MERCHANT_KYC_DETAILS_FAILURE',
  GET_MERCHANT_KYC_DETAILS_CLEAR: '@payouts/GET_MERCHANT_KYC_DETAILS_CLEAR',

  // create/update merchant kyc details
  POST_UPDATE_MERCHANT_KYC_DETAILS: '@payouts/POST_UPDATE_MERCHANT_KYC_DETAILS',
  POST_UPDATE_MERCHANT_KYC_DETAILS_REQUEST:
    '@payouts/POST_UPDATE_MERCHANT_KYC_DETAILS_REQUEST',
  POST_UPDATE_MERCHANT_KYC_DETAILS_SUCCESS:
    '@payouts/POST_UPDATE_MERCHANT_KYC_DETAILS_SUCCESS',
  POST_UPDATE_MERCHANT_KYC_DETAILS_FAILURE:
    '@payouts/POST_UPDATE_MERCHANT_KYC_DETAILS_FAILURE',
  POST_UPDATE_MERCHANT_KYC_DETAILS_CLEAR:
    '@payouts/POST_UPDATE_MERCHANT_KYC_DETAILS_CLEAR',
  // get payout transaction fail msg
  GET_PAYOUT_TRANSACTION_FAILED_MSG:
    '@payouts/GET_PAYOUT_TRANSACTION_FAILED_MSG',
  GET_PAYOUT_TRANSACTION_FAILED_MSG_REQUEST:
    '@payouts/GET_PAYOUT_TRANSACTION_FAILED_MSG_REQUEST',
  GET_PAYOUT_TRANSACTION_FAILED_MSG_SUCCESS:
    '@payouts/GET_PAYOUT_TRANSACTION_FAILED_MSG_SUCCESS',
  GET_PAYOUT_TRANSACTION_FAILED_MSG_FAILURE:
    '@payouts/GET_PAYOUT_TRANSACTION_FAILED_MSG_FAILURE',
  GET_PAYOUT_TRANSACTION_FAILED_MSG_CLEAR:
    '@payouts/GET_PAYOUT_TRANSACTION_FAILED_MSG_CLEAR',
};
